version: '3'

env:
  NODE_OPTIONS: '--no-warnings'
  APP_ENV: 'development'

dotenv: ['.env']

tasks:
  up:
    desc: Run the dev environment
    cmds:
      - process-compose up

  install:
    desc: Install dependencies
    dir: apps/dashboard
    cmds:
      - yarn install --prefer-offline --no-progress --non-interactive --silent
    sources:
      - package*.json
    generates:
      - node_modules

  run-api:
    desc: Run the go-api
    env:
      PORT: 3010
    cmds:
      - go tool gow run ./apps/api/cmd/main.go -e go,env

  run-worker:
    desc: Run the go-worker
    env:
      PORT: 3020
    cmds:
      - go tool gow run ./apps/worker/cmd/main.go -e go,env

  run-dashboard:
    desc: Run the go-dashboard
    deps: [install, gen-api-client]
    dir: apps/dashboard
    env:
      PORT: 3000
    cmds:
      - yarn vite

  gen-api-client:
    desc: Generate api client for the dashboard
    deps: [install]
    env:
      API_URL: http://localhost:3010/v1
    cmds:
      - go run cmd/admin/admin.go openapi > openapi.json
      - cd apps/dashboard && npx -y orval
      - cd apps/dashboard && npx -y biome check --unsafe --write src/lib/api/client.ts

  seed-clickhouse:
    desc: Seed ClickHouse
    cmds:
      - go run ./cmd/admin/admin.go seed-clickhouse

  lint:
    desc: Run Go linter
    cmds:
      - go fmt ./...
      - golangci-lint run ./...
