version: '3'

env:
  NODE_OPTIONS: '--no-warnings'
  APP_ENV: 'development'

dotenv: ['.env']

tasks:
  up:
    desc: Run the dev environment
    cmds:
      - process-compose up

  install:
    desc: Install dependencies
    cmds:
      - yarn --cwd ./apps/dashboard install --prefer-offline --no-progress --non-interactive --silent
    sources:
      - package*.json
    generates:
      - node_modules

  run-api:
    desc: Run the go-api
    cmds:
      - go tool gow run ./apps/api/cmd/main.go -e go,env

  run-worker:
    desc: Run the go-worker
    cmds:
      - go tool gow run ./apps/worker/cmd/main.go -e go,env

  run-dashboard:
    desc: Run the go-dashboard
    deps: [install]
    cmds:
      - yarn --cwd ./apps/dashboard dev

  seed-clickhouse:
    desc: Seed ClickHouse
    cmds:
      - go run ./cmd/admin/admin.go seed-clickhouse

  lint:
    desc: Run Go linter
    cmds:
      - go fmt ./...
      - golangci-lint run ./...
